routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Change Password Routes...
Route::get('change-password', 'Auth\ChangePasswordController@getChangePassword')->name('change-password');
Route::post('change-password', 'Auth\ChangePasswordController@postChangePassword')->name('change-password');

Route::group(['middleware' => 'auth'], function () {
    /*
     * Pages Routes
     */
    Route::get('/', 'CartController@index')->name('home');

    /*
     * Cart / Trasanction Draft Routes
     */
    Route::get('drafts', 'CartController@index')->name('cart.index');
    Route::get('drafts/{draftKey}', 'CartController@show')->name('cart.show');
    Route::post('drafts/{draftKey}', 'CartController@store')->name('cart.store');
    Route::post('cart/add-draft', 'CartController@add')->name('cart.add');
    Route::post('cart/add-draft-item/{draftKey}/{product}', 'CartController@addDraftItem')->name('cart.add-draft-item');
    Route::patch('cart/update-draft-item/{draftKey}', 'CartController@updateDraftItem')->name('cart.update-draft-item');
    Route::patch('cart/{draftKey}/proccess', 'CartController@proccess')->name('cart.draft-proccess');
    Route::delete('cart/remove-draft-item/{draftKey}', 'CartController@removeDraftItem')->name('cart.remove-draft-item');
    Route::delete('cart/empty/{draftKey}', 'CartController@empty')->name('cart.empty');
    Route::delete('cart/remove', 'CartController@remove')->name('cart.remove');
    Route::delete('cart/destroy', 'CartController@destroy')->name('cart.destroy');

    /*
     * Products Routes
     */
    Route::get('products/price-list', ['as' => 'products.price-list', 'uses' => 'ProductsController@priceList']);
    Route::resource('products', 'ProductsController', ['except' => ['create', 'show', 'edit']]);

    /*
     * Units Routes
     */
    Route::resource('units', 'UnitsController', ['except' => ['create', 'show', 'edit']]);

    /*
     * Users Routes
     */
    Route::resource('users', 'UsersController', ['except' => ['create', 'show', 'edit']]);

    /*
     * Transactions Routes
     */
    Route::get('transactions', ['as' => 'transactions.index', 'uses' => 'TransactionsController@index']);
    Route::get('transactions/{transaction}', ['as' => 'transactions.show', 'uses' => 'TransactionsController@show']);
    Route::get('transactions/{transaction}/pdf', ['as' => 'transactions.pdf', 'uses' => 'TransactionsController@pdf']);
    Route::get('transactions/{transaction}/receipt', ['as' => 'transactions.receipt', 'uses' => 'TransactionsController@receipt']);

    /*
     * Reports Routes
     */
    Route::group(['prefix' => 'reports'], function () {

        /*
         * Sales Routes
         */
        Route::get('sales', ['as' => 'reports.sales.index', 'uses' => 'Reports\SalesController@monthly']);
        Route::get('sales/daily', ['as' => 'reports.sales.daily', 'uses' => 'Reports\SalesController@daily']);
        Route::get('sales/monthly', ['as' => 'reports.sales.monthly', 'uses' => 'Reports\SalesController@monthly']);
        Route::get('sales/yearly', ['as' => 'reports.sales.yearly', 'uses' => 'Reports\SalesController@yearly']);
    });

    /*
     * Backup Restore Database Routes
     */
    Route::post('backups/upload', ['as' => 'backups.upload', 'uses' => 'BackupsController@upload']);
    Route::post('backups/{fileName}/restore', ['as' => 'backups.restore', 'uses' => 'BackupsController@restore']);
    Route::get('backups/{fileName}/dl', ['as' => 'backups.download', 'uses' => 'BackupsController@download']);
    Route::resource('backups', 'BackupsController', ['except' => ['create', 'show', 'edit']]);

    /*
     * Log Viewer routes
     */
    Route::get('log-files', ['as' => 'log-files.index', 'uses' => 'LogFilesController@index']);
    Route::get('log-files/{filename}', ['as' => 'log-files.show', 'uses' => 'LogFilesController@show']);
    Route::get('log-files/{filename}/download', ['as' => 'log-files.download', 'uses' => 'LogFilesController@download']);
});

app/Transaction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaction extends Model
{
    protected $casts = [
        'items'    => 'array',
        'customer' => 'array',
    ];

    public function getRouteKeyName()
    {
        return 'invoice_no';
    }

    public function getItemsCountAttribute($value)
    {
        $pcsCount = 0;
        foreach ($this->items as $item) {
            $pcsCount += $item['qty'];
        }

        return count($this->items).' Item, '.$pcsCount.' Pcs';
    }

    public function getExchange()
    {
        return $this->payment - $this->total;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\Transaction;
use Illuminate\Http\Request;

class TransactionsController extends Controller
{
    public function index(Request $request)
    {
        $q = $request->get('q');
        $date = $request->get('date');

        $transactions = Transaction::orderBy('invoice_no', 'desc')
            ->where(function ($query) use ($q, $date) {
                if ($q) {
                    $query->where('invoice_no', 'like', '%'.$q.'%');
                    $query->orWhere('customer', 'like', '%'.$q.'%');
                }
                if ($date) {
                    $query->where('created_at', 'like', $date.'%');
                }
            })->paginate(25);

        return view('transactions.index', compact('transactions', 'date'));
    }

    public function show(Transaction $transaction)
    {
        return view('transactions.show', compact('transaction'));
    }

    public function receipt(Transaction $transaction)
    {
        return view('transactions.receipt', compact('transaction'));
    }

    public function pdf(Transaction $transaction)
    {
        // return view('transactions.pdf', compact('transaction'));
        $pdf = PDF::loadView('transactions.pdf', compact('transaction'));

        return $pdf->stream($transaction->invoice_no.'.faktur.pdf');
    }
}

resources/views/transactions/index.blade.php
@extends('layouts.app')

@section('title', trans('transaction.list'))

@section('content')
<div class="panel panel-default">
    <div class="panel-heading">
        {{ Form::open(['method' => 'get','class' => 'form-inline pull-right']) }}
        {!! FormField::text('q', [
            'value' => request('q'),
            'label' => trans('transaction.search'),
            'class' => 'input-sm',
            'placeholder' => 'Ketik No. Invoice / Nama / Telp. Customer..',
            'style' => 'width:300px',
        ]) !!}
        {!! FormField::text('date', [
            'value' => request('date', $date),
            'label' => trans('app.date'),
            'class' => 'input-sm date-select',
            'placeholder' => 'yyyy-mm-dd',
        ]) !!}
        {{ Form::submit(trans('transaction.search'), ['class' => 'btn btn-sm']) }}
        {{ link_to_route('transactions.index', trans('app.reset')) }}
        {{ Form::close() }}
        <h3 class="panel-title" style="padding:6px 0">
            {{ trans('transaction.list') }} |
            {{ trans('app.total') }} : {{ $transactions->total() }} {{ trans('transaction.transaction') }}
        </h3>
    </div>
    <div class="panel-body">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>{{ trans('app.table_no') }}</th>
                    <th>{{ trans('transaction.invoice_no') }}</th>
                    <th>{{ trans('app.date') }}</th>
                    <th>{{ trans('transaction.customer') }}</th>
                    <th>{{ trans('transaction.items_count') }}</th>
                    <th class="text-right">{{ trans('transaction.total') }}</th>
                    <th class="text-center">{{ trans('app.action') }}</th>
                </tr>
            </thead>
            <tbody>
                @forelse($transactions as $key => $transaction)
                <tr>
                    <td>{{ $transactions->firstItem() + $key }}</td>
                    <td>{{ $transaction->invoice_no }}</td>
                    <td>{{ $transaction->created_at->format('Y-m-d') }}</td>
                    <td>
                        {{ $transaction->customer['name'] }}
                        {{ $transaction->customer['phone'] ? '(' . $transaction->customer['phone'] . ')' : '' }}
                    </td>
                    <td>{{ $transaction->items_count }}</td>
                    <td class="text-right">{{ formatRp($transaction->total) }}</td>
                    <td class="text-center">
                        {{ link_to_route('transactions.show', trans('app.show'), $transaction->invoice_no) }} |
                        {{ link_to_route('transactions.receipt', trans('app.print'), $transaction->invoice_no) }}
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="7">
                        Transaksi tidak ditemukan
                        @if (request('q'))
                            dengan keyword <em class="strong">{{ request('q') }}</em>
                        @endif
                        @if (request('date'))
                            dan pada tanggal <em class="strong">{{ request('date') }}</em>.
                        @endif
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
        <div>{!! str_replace('/?', '?', $transactions->appends(Request::except('page'))->render()) !!}</div>
    </div>
</div>
@endsection

@section('ext_css')
{!! Html::style(url('css/plugins/jquery.datetimepicker.css')) !!}
@endsection

@push('ext_js')
{!! Html::script(url('js/plugins/jquery.datetimepicker.js')) !!}
@endpush

@section('script')
<script>
(function() {
    $('.date-select').datetimepicker({
        timepicker: false,
        format:'Y-m-d',
        closeOnDateSelect: true
    });
})();
</script>
@endsection

resources/views/transactions/pdf.blade.php
@extends('layouts.pdf')

@section('title', $transaction->invoice_no.' - '.trans('transaction.invoice_print'))

@section('content')

<table style="width: 760px; border-collapse: collapse; page-break-inside: avoid; /*border:1px solid #aaa;*/">
    <tbody>
        <tr>
            <td colspan="3">
                <h2 class="text-center">{{ config('store.name') }}</h2>
                <p class="text-center">{{ config('store.address') }} | Telp: {{ config('store.phone') }}</p>
                <br>
                <table style="width:300px;margin: auto;">
                    <tbody>
                        <tr>
                            <td style="width:90px">{{ trans('transaction.invoice_no') }}</td>
                            <td>:</td>
                            <td class="strong">{{ $transaction->invoice_no }}</td>
                            <td class="text-right">{{ $transaction->created_at->format('d/m/Y') }}</td>
                        </tr>
                        <tr><td>{{ trans('transaction.cashier') }}</td><td>:</td><td>{{ $transaction->user->name }}</td><td class="text-right">{{ $transaction->created_at->format('H:i:s') }}</td></tr>
                        <tr><td>{{ trans('transaction.customer') }}</td><td>:</td><td colspan="2">{{ $transaction->customer['name'] }}</td></tr>
                        <tr><td>{{ trans('transaction.customer_phone') }}</td><td>:</td><td colspan="2">{{ $transaction->customer['phone'] }}</td></tr>
                    </tbody>
                </table>
                <br>
            </td>
        </tr>
        <?php $discountTotal = 0; ?>
        @foreach(collect($transaction->items)->chunk(30) as $chuncked30Items)
        <tr>
            @foreach($chuncked30Items->chunk(10) as $chunckedItems)
            <td style="width:250px;padding-right: 10px">
                <table class="main-table">
                    <tbody>
                        <tr><th colspan="3">@if ($loop->first) {{ trans('product.product') }} @else &nbsp; @endif</th></tr>
                        <tr>
                            <th class="">@if ($loop->first) {{ trans('product.item_qty') }} @else &nbsp; @endif</th>
                            <th class="text-right">@if ($loop->first) {{ trans('product.price') }} ({{ trans('product.item_discount') }}) @else &nbsp;<br>&nbsp; @endif</th>
                            <th class="text-right" style="width:90px">@if ($loop->first) {{ trans('product.item_subtotal') }} @else &nbsp; @endif</th>
                        </tr>
                        @foreach($chunckedItems as $key => $item)
                        <tr>
                            <td class="strong" colspan="3">{{ $key + 1 }})&nbsp;{{ $item['name'] }} ({{ $item['unit'] }})</td>
                        </tr>
                        <tr>
                            <td class="text-center border-bottom">{{ $item['qty'] }}</td>
                            <td class="text-right border-bottom">
                                {{ formatRp($item['price']) }}<br>({{ formatRp($item['item_discount']) }})
                            </td>
                            <td class="text-right border-bottom">{{ formatRp($item['subtotal']) }}</td>
                        </tr>
                        <?php $discountTotal += $item['item_discount_subtotal'] ?>
                        @endforeach
                        @if ($loop->last && $loop->parent->last)
                        <tr>
                            <th colspan="2" class="text-right">{{ trans('transaction.subtotal') }} :</th>
                            <th class="text-right">{{ formatRp($transaction['total'] + $discountTotal) }}</th>
                        </tr>
                        <tr>
                            <th colspan="2" class="text-right">{{ trans('transaction.discount_total') }} :</th>
                            <th class="text-right">{{ formatRp($discountTotal) }}</th>
                        </tr>
                        <tr>
                            <th colspan="2" class="text-right">{{ trans('transaction.total') }} :</th>
                            <th class="text-right">{{ formatRp($transaction['total']) }}</th>
                        </tr>
                        <tr>
                            <th colspan="2" class="text-right">{{ trans('transaction.payment') }} :</th>
                            <th class="text-right">{{ formatRp($transaction->payment) }}</th>
                        </tr>
                        <tr>
                            <th colspan="2" class="text-right">{{ trans('transaction.exchange') }} :</th>
                            <th class="text-right">{{ formatRp($transaction->getExchange()) }}</th>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </td>
            @endforeach
        </tr>
        @endforeach
    </tbody>
</table>
@endsection

resources/views/transactions/receipt.blade.php
@extends('layouts.pdf')

@section('title', $transaction->invoice_no.' - '.trans('transaction.invoice_print'))

@section('style')
<style>
    table.receipt-table {
        width: 310px;
        border-collapse: collapse;
    }
    table.receipt-table th {
        padding: 5px 0;
    }
    table.receipt-table td {
        padding: 3px 0;
    }
</style>
@endsection

@section('content')

<table class="receipt-table">
    <tbody>
        <tr><td colspan="3"><h2 class="text-center">{{ config('store.name') }}</h2></td></tr>
        <tr>
            <td colspan="3">
                <p class="text-center">{{ config('store.address') }} | Telp: {{ config('store.phone') }}</p>
            </td>
        </tr>
        <tr>
            <td style="width:90px">{{ trans('transaction.invoice_no') }}</td>
            <td class="strong">: {{ $transaction->invoice_no }}</td>
            <td class="text-right">{{ $transaction->created_at->format('d/m/Y') }}</td>
        </tr>
        <tr>
            <td>{{ trans('transaction.cashier') }}</td>
            <td>: {{ $transaction->user->name }}</td>
            <td class="text-right">{{ $transaction->created_at->format('H:i:s') }}</td>
        </tr>
        <tr><td>{{ trans('transaction.customer') }}</td><td colspan="2">: {{ $transaction->customer['name'] }}</td></tr>
        <tr><td>{{ trans('transaction.customer_phone') }}</td><td colspan="2">: {{ $transaction->customer['phone'] }}</td></tr>
        <tr><th colspan="3" class="text-left">{{ trans('transaction.items') }}</th></tr>
        <tr>
            <th class="border-bottom">{{ trans('product.item_qty') }}</th>
            <th class="text-right border-bottom">{{ trans('product.price') }} ({{ trans('product.item_discount') }})</th>
            <th class="text-right border-bottom" style="width:90px">{{ trans('product.item_subtotal') }}</th>
        </tr>
        <?php $discountTotal = 0; ?>
        @foreach($transaction->items as $key => $item)
        <tr>
            <td class="strong" colspan="3">{{ $key + 1 }})&nbsp;{{ $item['name'] }} ({{ $item['unit'] }})</td>
        </tr>
        <tr>
            <td class="text-center border-bottom" style="vertical-align: top;">{{ $item['qty'] }}</td>
            <td class="text-right border-bottom">
                {{ formatRp($item['price']) }} ({{ formatRp($item['item_discount']) }})
            </td>
            <td class="text-right border-bottom">{{ formatRp($item['subtotal']) }}</td>
        </tr>
        <?php $discountTotal += $item['item_discount_subtotal'] ?>
        @endforeach
        <tr>
            <th colspan="2" class="text-right">{{ trans('transaction.subtotal') }} :</th>
            <th class="text-right">{{ formatRp($transaction['total'] + $discountTotal) }}</th>
        </tr>
        <tr>
            <th colspan="2" class="text-right">{{ trans('transaction.discount_total') }} :</th>
            <th class="text-right">{{ formatRp($discountTotal) }}</th>
        </tr>
        <tr>
            <th colspan="2" class="text-right">{{ trans('transaction.total') }} :</th>
            <th class="text-right">{{ formatRp($transaction['total']) }}</th>
        </tr>
        <tr>
            <th colspan="2" class="text-right">{{ trans('transaction.payment') }} :</th>
            <th class="text-right">{{ formatRp($transaction->payment) }}</th>
        </tr>
        <tr>
            <th colspan="2" class="text-right">{{ trans('transaction.exchange') }} :</th>
            <th class="text-right">{{ formatRp($transaction->getExchange()) }}</th>
        </tr>
    </tbody>
</table>
@endsection

resources/views/transactions/show.blade.php
@extends('layouts.app')

@section('title', $transaction->invoice_no . ' - ' . trans('transaction.detail'))

@section('content')
<div class="pull-right">
    {{ link_to_route('transactions.pdf', trans('transaction.invoice_pdf'), [$transaction->invoice_no], ['class' => 'btn btn-default']) }}
    {{ link_to_route('transactions.receipt', trans('transaction.invoice_print'), [$transaction->invoice_no], ['class' => 'btn btn-default']) }}
</div>
<h3 class="page-header">{{ $transaction->invoice_no }} <small>{{ trans('transaction.detail') }}</small></h3>
<div class="row">
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">{{ trans('transaction.detail') }}</h3></div>
            <div class="panel-body">
                <table class="table table-condensed">
                    <tbody>
                        <tr><td>{{ trans('transaction.invoice_no') }}</td><td class="text-primary strong">{{ $transaction->invoice_no }}</td></tr>
                        <tr><td>{{ trans('app.date') }}</td><td>{{ $transaction->created_at->format('Y-m-d') }}</td></tr>
                        <tr><td>{{ trans('transaction.customer_name') }}</td><td>{{ $transaction->customer['name'] }}</td></tr>
                        <tr><td>{{ trans('transaction.customer_phone') }}</td><td>{{ $transaction->customer['phone'] }}</td></tr>
                        <tr><td>{{ trans('transaction.items_count') }}</td><td>{{ $transaction->items_count }}</td></tr>
                        <tr><td>{{ trans('transaction.total') }}</td><td class="text-right strong">{{ formatRp($transaction->total) }}</td></tr>
                        <tr><td>{{ trans('transaction.payment') }}</td><td class="text-right">{{ formatRp($transaction->payment) }}</td></tr>
                        <tr><td>{{ trans('transaction.exchange') }}</td><td class="text-right">{{ formatRp($transaction->getExchange()) }}</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">{{ trans('transaction.items') }}</h3></div>
        <div class="panel-body">
            <table class="table table-condensed">
            <thead>
                <tr>
                    <th>{{ trans('app.table_no') }}</th>
                    <th>{{ trans('product.name') }}</th>
                    <th class="text-right">{{ trans('product.item_price') }}</th>
                    <th class="text-right">{{ trans('product.item_discount') }}</th>
                    <th class="text-center">{{ trans('product.item_qty') }}</th>
                    <th class="text-right">{{ trans('product.item_subtotal') }}</th>
                </tr>
            </thead>
            <tbody>
            <?php $discountTotal = 0; ?>
            @foreach($transaction->items as $key => $item)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>
                        {{ $item['name'] }} <br>
                        <small class="text-primary">({{ $item['unit'] }})</small>
                    </td>
                    <td class="text-right">{{ formatRp($item['price']) }}</td>
                    <td class="text-right">{{ formatRp($item['item_discount']) }}</td>
                    <td class="text-center">{{ $item['qty'] }}</td>
                    <td class="text-right">{{ formatRp($item['subtotal']) }}</td>
                </tr>
                <?php $discountTotal += $item['item_discount_subtotal'] ?>
            @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="5" class="text-right">{{ trans('transaction.subtotal') }} :</th>
                    <th class="text-right">{{ formatRp($transaction['total'] + $discountTotal) }}</th>
                </tr>
                <tr>
                    <th colspan="5" class="text-right">{{ trans('transaction.discount_total') }} :</th>
                    <th class="text-right">{{ formatRp($discountTotal) }}</th>
                </tr>
                <tr>
                    <th colspan="5" class="text-right">{{ trans('transaction.total') }} :</th>
                    <th class="text-right">{{ formatRp($transaction['total']) }}</th>
                </tr>
            </tfoot>
        </table>
        </div>
    </div>
    </div>
</div>
@endsection